### ISSUE TITLE
Problem with contributing items

### ISSUE THREAD

**Issue by ShmielB** [Compuskills-Jerusalem/shuk-routing#12]
As it was discussed in issue #3 and #11  that we should have a drop down menu with all the stall names one because it should be easier to contribute ,  i assume we would have the same drop down menu for the items when contributing a item ,
The second reason we need to have a drop down menu is because the way the database is now designed in the **Commoditie Stalls** table there must be a **Stall ID** and a **Commoditie ID** ,  so the Stall and the Commodity must be in the database before afterwards you can add an existing commodity to an existing stall , 

_The_ _problem_ _is when someone wants to add an item that is not in the system or to a store that is not in the system they wont bother and add the item ( Commodity ) or the store before, very likely to just leave with out adding anything at all_.

**Comment by hershyd** [comment]
so if someone wants to add an item to a store, and the item dose not exist at all in the system/database, the item should **automatically** be added as a new commodity in the Commodities table, and not be required to manually create the item, in the create item section of the program.
and vice versa if someone wants to add a item to a store and the **store** does not exist in the database.

**Comment by ykahan** [comment]
@hershyd @ShmielB 
This is an issue, I agree, but let's put in a sanity check--ask the user if he really wants to create something new.  Otherwise, we'll be adding stuff every time someone mispells a commodity or stall that already exists.

Upon further thought and in-class discussion, allowing the user to actually add something to the database creates a lot of risk, and just adding a "Do you want to add this?" popup doesn't fix it.  He might actually think that "wine" is spelled "winne," for example.  For the MVP, my recommendation is that the user have no ability to actually add new commodities or stalls to our working database, but merely to add them to a "To Be Added" database, from which administration can manually decide what actually goes in.  Of course, the user should still be able to add reviews and prices to existing stalls/commodity combos.

**Comment by ShmielB** [comment]
Great sounds good ill work on the UI part @Jatudrei  please if you can add a table to the db for the Be Added list .

Please add a comment when your done with the db table , Thanks .

**Comment by ShmielB** [comment]
This issue is broken up to two new issues #13 and #22  .

Basically what we ended up with in this issue like @ykahan suggested that for the MVP we don't want to trust the users input to add a new Commodity or Stall ,
just it will be added to a "To be added" table , for what there is a new issue for to create the tables **issue #13 Create new tables** ,
and issue #22 the logic of the program to check if there is that product / stall in the Data Base and the logic how to added to the to be added table .
